bdk:
  host: HOST_URL
  bot:
    username: bdk-integration-tests-worker-bot-TEST1
    privateKey:
      path: rsa/privatekey.pem

  datafeed:
    version: v1
logging:
  level:
    com.symphony: debug
